---
- name: Create systemd drop-in
  when: coturn_listening_port|int < 1024 or coturn_tls_listening_port|int < 1024
  block:
    - name: Systemd drop-in directory present
      ansible.builtin.file:
        state: directory
        path: /etc/systemd/system/coturn.service.d
        owner: root
        group: root
        mode: "0755"

    - name: Listening on privileged port granted
      ansible.builtin.copy:
        src: systemd-cap-net-bind-override.conf
        dest: /etc/systemd/system/coturn.service.d/01-cap-net-bind.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Reload systemd
        - Restart coturn

- name: Allow listing on privileged ports
  when: coturn_listening_port|int >= 1024 and coturn_tls_listening_port|int >= 1024
  block:
    - name: Listening on privileged port not granted
      ansible.builtin.file:
        path: /etc/systemd/system/coturn.service.d/01-cap-net-bind.conf
        state: absent
      notify:
        - Reload systemd
        - Restart coturn
